version = "1"

slug = "ug"
title = "Ug!"
description = """
Feel the Ug! A 10k collection of unique, hand-drawn, exclusive NFTs, drawn by Squashua - with Collector Appreciation rewards, and a range of perks!
"""

[[source]]
type = "cardano"
policy_id = "8972aab912aed2cf44b65916e206324c6bdcb6fbd3dc4eb634fdbd28"

[[link]]
type = "discord"
invite_code = "Xm2BEsvu9W"

[[link]]
type = "x"
account = "ugvsdonut"

[[link]]
type = "website"
url = "https://www.squashua.io/"
