name: Create Collection PR

on:
  workflow_run:
    workflows: ["Trigger PR Creation"]
    types:
      - completed

permissions:
  contents: write
  pull-requests: write

jobs:
  create-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Download slug artifact
        uses: actions/download-artifact@v4
        with:
          name: slug

      - name: Read slug
        id: slug
        run: |
          SLUG=$(cat slug.txt | xargs)
          echo "slug=$SLUG" >> $GITHUB_OUTPUT

      - name: Check if branch already exists
        run: |
          BRANCH="collection/${{ steps.slug.outputs.slug }}"
          if git ls-remote --exit-code --heads origin "$BRANCH"; then
            echo "Branch $BRANCH already exists. Exiting."
            exit 0
          fi

      - name: Prepare collection files
        run: |
          mkdir -p collections/${{ steps.slug.outputs.slug }}
          cp template/collection/*.toml collections/${{ steps.slug.outputs.slug }}/

      - name: Bootstrap config and open PR
        uses: peter-evans/create-pull-request@v5
        with:
          title: "New Collection: ${{ steps.slug.outputs.slug }}"
          branch: "collection/${{ steps.slug.outputs.slug }}"
          base: main
          draft: true
          commit-message: "Bootstrap collection ${{ steps.slug.outputs.slug }}"
          add-paths: |
            collections/${{ steps.slug.outputs.slug }}/*
