name: Create Collection PR

on:
  push:
    branches:
      - "collection/**"

permissions:
  contents: write
  pull-requests: write

jobs:
  create-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Extract slug from branch
        id: extract
        run: |
          BRANCH="${GITHUB_REF##refs/heads/}"
          SLUG="${BRANCH#collection/}"
          echo "slug=$SLUG" >> $GITHUB_OUTPUT

      - name: Open PR
        uses: peter-evans/create-pull-request@v5
        with:
          title: "New Collection: ${{ steps.extract.outputs.slug }}"
          branch: ${{ github.ref_name }}
          base: main
          draft: true
          commit-message: "Bootstrap collection ${{ steps.extract.outputs.slug }}"
          add-paths: |
            collections/${{ steps.extract.outputs.slug }}/*
