name: Manually Upload Collection to Curator

on:
  workflow_dispatch:
    inputs:
      policy_id:
        description: "Cardano policy ID (used to locate collection folder)"
        required: true
        type: string

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build curator
        id: build_curator
        uses: ./.github/actions/build-curator

      - name: Submit collection for ${{ github.event.inputs.policy_id }}
        run: |
          POLICY_ID=${{ github.event.inputs.policy_id }}
          FILE="collections/cardano/$POLICY_ID/overview.toml"

          if [ ! -f "$FILE" ]; then
            echo "❌ overview.toml not found at $FILE"
            exit 1
          fi

          echo "📦 Uploading collection $POLICY_ID..."
          ${{ steps.build_curator.outputs.curator-path }} update "$FILE"
