name: Validate TOML Files

on:
  pull_request:
    paths:
      - "**/*.toml"

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache Rust build
        uses: actions/cache@v4
        with:
          path: |
            tools/curator/target
          key: rust-validate-${{ runner.os }}-${{ hashFiles('tools/curator/Cargo.lock', 'tools/curator/src/**/*.rs') }}
          restore-keys: |
            rust-validate-${{ runner.os }}-${{ hashFiles('tools/curator/Cargo.lock', 'tools/curator/src/**/*.rs') }}

      - name: Build curator (only if needed)
        working-directory: tools/curator
        run: |
          if [ -f target/release/validatocurator ]; then
            echo "✅ Curator already built from cache"
          else
            echo "🔨 Building curator..."
            cargo build --release
          fi

      - name: Get changed TOML files via GitHub API
        id: get_files
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          PR_NUMBER=$(jq .pull_request.number "$GITHUB_EVENT_PATH")
          FILES=$(gh pr view "$PR_NUMBER" --json files --jq '.files[].path' | grep '\.toml$' || true)
          echo "files=${FILES//$'\n'/,}" >> "$GITHUB_OUTPUT"

      - name: Run curator validation
        if: steps.get_files.outputs.files != ''
        run: |
          IFS=',' read -ra FILES <<< "${{ steps.get_files.outputs.files }}"
          ./tools/curator/target/release/curator validate "${FILES[@]}"
