name: Validate TOML Files

on:
  pull_request:
    paths:
      - "**/*.toml"

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache Rust build
        uses: actions/cache@v4
        with:
          path: |
            tools/validator/target
          key: rust-validate-${{ runner.os }}-${{ hashFiles('tools/validator/Cargo.lock', 'tools/validator/src/**/*.rs') }}
          restore-keys: |
            rust-validate-${{ runner.os }}-

      - name: Build validator
        working-directory: tools/validator
        run: cargo build --release

      - name: Run validation
        run: |
          FILES=$(git diff --name-only origin/${{ github.base_ref }}...HEAD | grep '\.toml$' || true)
          if [ -n "$FILES" ]; then
            ./tools/validate-toml/target/release/validate-toml $FILES
          fi
